set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# set shell sessions
set -g default-shell "/bin/zsh"

# remap prefix
set -g prefix C-a; unbind C-a; bind-key C-a send-prefix

# index for windows and panes
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# status line
set -g status-style "bg=black,fg=white"
set -g status-left-length 40
set -g status-left "#[default] [#S] "
set -g status-right "%Y-%m-%d %H:%M #[default]"
set -g status-justify centre

# status line activity
set -g monitor-activity on
set -g status-interval 60
set -g visual-activity on
setw -g monitor-silence 15

# status text format, inactive
set -g window-status-format "#[fg=white] #I:#W #F"

# status text format, active
set -g window-status-current-format "#[fg=gray] #I:#W #F"

# pane colors
set -g pane-border-style fg=green,bg=black
set -g pane-active-border-style fg=white,bg=yellow

# message colors
set -g message-style bright,fg=white,bg=black

# create splits/windows
unbind '%'; bind | split-window -h -c "#{pane_current_path}"
unbind '"'; bind '-' split-window -v -c "#{pane_current_path}"
unbind c; bind c new-window -c "#{pane_current_path}"

# reload .tmux.conf
unbind r; bind r source-file ~/.tmux.conf;

# select pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize pane
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5
bind -r m resize-pane -Z

set -g focus-events on
