tap 'homebrew/bundle'
tap 'homebrew/services'

brew 'git'
brew 'heroku-toolbelt'
brew 'irssi'
brew 'jq'
brew 'nodenv'
brew 'postgresql'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'ruby-build'
brew 'tmux'
brew 'tree'
brew 'vim', args: ['with-override-system-vim']

tap 'caskroom/cask'
cask '1password'
cask 'atom'
cask 'cloak'
cask 'docker'
cask 'dropbox'
cask 'flux'
cask 'google-chrome'
cask 'ngrok'
cask 'postman'
cask 'screenhero'
cask 'vlc'

tap 'caskroom/fonts'
cask 'font-inconsolata'
